//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.04 at 09:53:48 AM IST 
//


package com.example.jaxb.jaxbmarshaller.bean;

import jakarta.xml.bind.annotation.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for providerMaintenanceServiceIBRequestRoot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="providerMaintenanceServiceIBRequestRoot"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ust-global.com/schema/common}header"/&gt;
 *         &lt;element name="providerMaintenanceServiceIBRequest" type="{http://www.ust-global.com/schema/providermaintenance}providerMaintenanceServiceIBRequest" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "providerMaintenanceServiceIBRequestRoot", propOrder = {
    "header", "requests"
})
@NoArgsConstructor
@Data
public class ProviderMaintenanceServiceIBRequestRoot {

    @XmlElement
    protected Header header;

    @XmlElement
    protected List<Request> requests;

}
