management:
  health:
    circuitbreakers:
      enabled : true
  endpoints:
    web:
      exposure:
        include : health
  endpoint:
    health:
      show-details : always

resilience4j.circuitbreaker:
  instances:
    studentService:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 5
#      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED

#resilience4j.circuitbreaker:
#  configs:
#    default:
#      registerHealthIndicator : true
#      eventConsumerBufferSize : 10
#      minimumNumberOfCalls : 5
#      failureRateThreshold : 50
#      waitDurationInOpenState : 2
#      automaticTransitionFromOpenToHalfOpenEnabled : true
#      permittedNumberOfCallsInHalfOpenState : 3
#      slidingWindowSize : 10
#      slidingWindowType : COUNT_BASED
#  instances:
#    studentService:
#      baseConfig: default